name: listzen

version: 1.0.0+12

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.0
  cloud_firestore: ^4.8.5
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  uuid: ^3.0.7
  rxdart: ^0.27.7
  flutter_hooks: ^0.20.0
  flutter_slidable: ^3.0.0
  flutter_keyboard_visibility: ^5.4.1
  awesome_snackbar_content: ^0.1.3
  sqflite: ^2.3.0
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  floating_draggable_widget: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  lint: ^2.1.2
  flutter_native_splash: ^2.3.2
  drift_dev: ^2.13.0

flutter_native_splash:
  background_image: assets/main_image.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/main_image.jpg
    - icons/
  fonts:
    - family: Architex
      fonts:
        - asset: fonts/Architex.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf