name: success_check
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^6.0.5
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter_bloc: ^8.1.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^6.0.2
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  kt_dart: ^1.0.0
  uuid: ^3.0.7
  rxdart: ^0.27.7
  another_flushbar: ^1.12.29
  flutter_flushbar: ^0.0.2
  flutter_hooks: ^0.18.6
  flutter_slidable: ^2.0.0
  flutter_keyboard_visibility: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.0.3
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sticky_note.jpg
    - icons/google.png
  fonts:
    - family: Architex
      fonts:
        - asset: fonts/Architex.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf