name: listzen

version: 1.0.0+19

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  cloud_firestore: ^4.13.5
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  uuid: ^4.2.1
  rxdart: ^0.27.7
  flutter_hooks: ^0.20.3
  flutter_slidable: ^3.0.1
  awesome_snackbar_content: ^0.1.3
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  floating_draggable_widget: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  lint: ^2.2.0
  flutter_native_splash: ^2.3.8
  drift_dev: ^2.14.0

flutter_native_splash:
  color: "#0097b2"
  image: assets/splash.png
  web: false
  ios: true
  android: true
  android_12:
    color: "#0097b2"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - icons/
  fonts:
    - family: Architex
      fonts:
        - asset: fonts/Architex.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf