name: success_check
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  injectable: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  lint: ^2.0.1

flutter:
  uses-material-design: true
